### PR TITLE
Adding a new section to demonstrate Pandas table joins 

### PR DESCRIPTION
**Pull request by galaxyumi**
Added a new section 5 to describe how to do Pandas table join between a user-created table and the DP0.3 retrieved table.

### CODE REVIEW

**Review by MelissaGraham — CHANGES_REQUESTED** [review]
Thanks for doing this, I found a few things.

S.5.2, the print statement at the end of S.5.2 is too long (127 characters) max line length is 99.

S.5.3, recommend to add a print(len(ut4), len(results), len(merged_df)) statement, which results in 1000 447679 81, and to mention that "inner" join means matches only.

S.5.3, recommend to show (or have option to show) the merged table so users can see its final format.

S.5.3, last cell has some pycodestyle violations (too-long line, whitespace)

S.5.3.1, figure needs a caption; add space between colon and object name in title

Plots: use LSST filter colors defined in https://rtn-045.lsst.io/#colorblind-friendly-plots.  

Suggestion: S.5.3.1 and its plot aren't making use of the fact that the table was merged… I think the plot could have been made with the results table alone yeah? So I think the tutorial could end at displaying the merged table, or the tutorial could change the contents of the merged table to enable a visualization that relies on the data from both tables that were merged. Thoughts?

**Comment by galaxyumi** [comment]
Thank you @MelissaGraham for your feedback. 

Regarding your last suggestion: how about replacing the current plot with a new plot comparing the orbital parameters from the Gaia table and the MPCORB table for the merged table?

**Comment by MelissaGraham** [comment]
> Thank you @MelissaGraham for your feedback.
> 
> Regarding your last suggestion: how about replacing the current plot with a new plot comparing the orbital parameters from the Gaia table and the MPCORB table for the merged table?

That sounds like a good demo!

**Comment by galaxyumi** [comment]
@MelissaGraham I implemented all your feedback and took a workaround by using fullDesignation instead of mpcDesignation for table joins. The NB is ready for the final review.

**Review by MelissaGraham — APPROVED** [review]
good to go!

**Pull request merged**
