### PR TITLE
PREOPS-3344

### PR DESCRIPTION
**Pull request by plazas**

### CODE REVIEW

**Review by MelissaGraham — CHANGES_REQUESTED** [review]
See Jira ticket comments.

**Comment by jeffcarlin** [comment]
Hi Andres - mostly looks good. I added a few new comments on the Jira ticket.

**Review by jeffcarlin — APPROVED** [review]
Mostly looks good, Andres. I added a few comments on the Jira ticket.

**Comment by ryanlauastro** [comment]
Hi Andres, sorry for the delay on the review. Please see my comments on the Jira ticket.

**Review by MelissaGraham — APPROVED** [review]

**Pull request merged**
