### PR TITLE
tickets/PREOPS-3560: create a DP0.3 tutorial notebook on Main Belt Asteroids

### PR DESCRIPTION
**Pull request by jeffcarlin**

### CODE REVIEW

**Comment by ameisner** [comment]
@jeffcarlin would it be possible to add an explicit statement of what the color map is/means in plots like the one shown below? My impression is that the color map is density of objects, but that would be good to mention, especially since I don't believe the literature plots like parker2008_orbit_families_sini_vs_a.png are colored by object density.

Aside from this request, there are a number of very minor edits that I can make myself via commits on this branch later today. Thanks...

Screen Shot 2023-07-12 at 4 00 28 AM (2)

**Review by ameisner — CHANGES_REQUESTED** [review]
“DP0.3_01_Introduction_to_DP0.3” - change to “DP03_01_Introduction_to_DP0.3” for consistency of naming convention with what Melissa set up

Definition of “xyz_orbit_plot_manyobjects” - title keyword arg not documented in docstring

Units (?) warning. I think we're supposed to add a not in the tutorial if there's a non-catastrophic warning to be expected:

Screen Shot 2023-07-12 at 5 34 43 PM (2)


“semi-major axes between the Earth and Jupiter.” - saying “Mars and Jupiter” here would be better (https://en.wikipedia.org/wiki/Asteroid_belt)

“2.2 Main Belt Asteroids -- Objects outside Earth's orbit (a > 1 AU) and inside Jupiter's position (a < 5 AU)” - again, Earth -> Mars, also make “asteroids” lower case for consistency

“ For the rest of this notebook, we will focus on the so-called "Main Belt" asteroids with semi-major axes between the Earth and Jupiter. “ - repeat of earlier sentence where Earth should be switched to Mars

“ (For example, at a=2.5 AU, an asteroid orbits 3 times for each single orbit of Jupiter, and is thus in a "3:1 resonance".” - stray opening parenthesis “(“ character here, delete this

May want to clarify that this notebook is adopting 1-5 AU as an approximate “Main Belt” a range, but this isn’t really standard (see https://en.wikipedia.org/wiki/Asteroid_belt#Periphery for some nominal boundaries)

“The following figure is from the [Grav et al. 2011 paper](https://ui.adsabs.harvard.edu/abs/2011PASP..123..423G/abstracthttps://ui.adsabs.harvard.edu/abs/2011PASP..123..423G/abstract)” - Grav link is duplicated, needs fixing, also don’t see mention in this paper of the 1.5 to 5 AU definition stated

“those with orbital semi-major axes between 1-5 AU, and with pericenters larger than 1.5 AU” - suggest “pericenter” -> “perihelion” here

“This figure shows the orbital inclinations and eccentricities of "Main Belt Asteroids" (i.e., those with orbital semi-major axes between 1-5 AU, and with pericenters larger than 1.5 AU)” - make “asteroids” lower case here for consistency

Re: the 1.5 AU lower limit:
​​https://academic.oup.com/mnras/article/465/4/4381/2556160 - this says “We adopt the boundaries of the main asteroid belt as a(1 − e) > 1.6 au and a < 3.8 au. This definition, which is similar to one adopted in many previous studies, excludes asteroids with perihelion distance smaller than Mars’ aphelion as well as the Hilda group and the Trojan asteroids (in 3:2 and 1:1 MMR with Jupiter, respectively).”

So suggest increasing semi-major axis lower limit to 1.6

“not_near_earth_peri” - I think the important thing here is for perihelion to not make it cross *Mars*, not Earth

“apologies for the low resolution” - maybe a future task/ticket could be to make a less blurry version of this figure (by doing some editing in e.g., Preview)

Colormap of the figures not explained in text (already made GitHub comment about this one)

“Figure out whether the Main Belt asteroids with perihelion distance less than 1.5 AU make a close approach to the Earth.” - don’t think we should say there’s such a thing as main belt asteroids with q < 1.5 AU (see above about definition of main belt). suggest deleting this optional exercise

**Comment by jeffcarlin** [comment]
> Units (?) warning. I think we're supposed to add a note in the tutorial if there's a non-catastrophic warning to be expected:

In this case I think it'll go away in the final version of DP0.3. They're supposed to be fixing all the units.

**Comment by jeffcarlin** [comment]
Thanks for the helpful review, Aaron! I think I've addressed all the comments in the version that I just pushed. Let me know if you spot anything I missed.

**Comment by ameisner** [comment]
Thanks, will take a look at it very soon!

**Comment by ameisner** [comment]
I see outer main belt threshold values of 4.2 AU and 4.3 AU now in the notebook, but not in the Malhotra paper's text? Where do these values come from? The Malhotra paper says a < 3.8 AU.

Also, regarding:

> 2.2 Main Belt asteroids -- Objects outside Mars's orbit (a > 1.6 AU)

The "a > 1.6 AU" should be "q > 1.6 AU" here.

I'm going to ask Pedro what he recommends quoting for the outer edge of the main belt before going any further -- there doesn't appear to be uniform consensus in outer thresholds adopted.

**Review by ameisner — APPROVED** [review]

**Pull request merged**
