### PR TITLE
Tickets/preops 3559

### PR DESCRIPTION
**Pull request by plazas**

### CODE REVIEW

**Review by ryanlauastro — CHANGES_REQUESTED** [review]
Hi Andres, 

The notebook looks good to me, here are some comments and suggested changes from my review:

Sec. 1.1: For the description of "higher eccentricities" for the "Hot" TNOs, it might be good to provide an example of how much higher.

Sec. 1.1.2: "..., far away from the sun" -> "..., far away from the Sun"

Sec. 2.1: In the wikipedia link, I think the link is double pasted and is therefore not going to the right page

Sec. 3: right before the 2nd cell "...visualization libray to plot plot the eccentricy and inclination..." -- library and eccentricity have typos and "plot" is listed twice.

Sec. 3: Plot from the 2nd cell -- you could add a "plt.show()" at the end to get rid of that "Text(0, 0.5, 'inclination (degrees)')"

Sec. 3.1, first paragraph "Warning": I think "Gladmann" is spelt with only one "n" ->"Gladman"

Sec.3.3.2, first paragraph: The abstract of Vilenius et al. seems to indicate that the average albedos is 0.17 +/- 0.04 (at least for the cold classicals). But perhaps this is not the value that's being adopted.

Sec.3.3.2, first paragraph: Another note on the estimateDiameter function -- it looks like the default albedo value is 0.15 when estimateDiameter is being defined. Would it make more sense to revise the function above such that the default value is 0.1 instead of 0.15?

Sec.3.3.2, first paragraph: "...is expected to ave smaller sizes..." -> "...is expected to have smaller sizes..."

Sec. 4.2, first sentence: "teh" -> "the"

Sec. 5. first paragraph: "catalogto" ->"catalog to"

Sec. 5, last sentence: "inthe" -> "in the"

Sec. 6., point 1: "the the" -> "the"

**Comment by plazas** [comment]
Thanks, Ryan, I have addressed the comments and left responses in Jira.

**Comment by ryanlauastro** [comment]
No problem, OK, I'll have a look through it now.

**Comment by ryanlauastro** [comment]
made some minor typo edits to author names on the references. Looks good to go to me!

**Review by ryanlauastro — APPROVED** [review]

**Comment by plazas** [comment]
Thanks, Ryan! I have run `flake8-nb` a last time before merging and things seem fine.

**Pull request merged**
