### PR TITLE
Notebook 03a

### PR DESCRIPTION
**Pull request by kadrlica**
This is a PR for the new notebook 03a on image display and manipulation using afwDisplay.

### CODE REVIEW

**Comment by kadrlica** [comment]
This should run "as is" on `[data-int](https://data-int.lsst.cloud/)` and it should also run on `[data](https://data.lsst.cloud/)` **if** you replace `config='dp02'` with `config='dp02-test'`.

**Comment by DouglasLeeTucker** [comment]
I've reviewed the updated notebook, and it looks good!  I particularly like the inclusion of anchor points to link back to functions that were defined earlier in the notebook (e.g., for `cutout_coadd` and for `create_rgb`.

I just found 3 minor errors and typos:

1. It looks like the **Packages** cell at the beginning of the notebook has not yet been updated.
2. Under the **Get Support** cell at the beginning of the notebook, there is an old link to dp0-1.lsst.io (https://dp0-1.lsst.io/) that should be updated to dp0-2.lsst.io (https://dp0-2.lsst.io/).
3. In Section 5, paragraph 5, the final sentence, there is a typo (“tutuorials” --> “tutorials”).

Other than those very minor issues, looks great!

**Comment by DouglasLeeTucker** [comment]
I also just now confirmed that the notebook NB03a works on data.lsst.cloud if one just changes config from `dp02` to `dp02-test`.

**Review by DouglasLeeTucker — COMMENTED** [review]
Looks good!  I already merged it.  Thanks, Alex!

**Pull request merged**
