### PR TITLE
Survey Property Maps Visualization

### PR DESCRIPTION
**Pull request by kadrlica**
This is an adaptation from Eli's notebook on visualizing survey properties using healsparse and skyproj. Thanks to Melissa for her additions!

### CODE REVIEW

**Comment by kadrlica** [comment]
@erykoff are you willing to take a look at this (looks like you aren't in the `rubin-dp0` org, so I can't assign you as a formal reviewer).

**Comment by erykoff** [comment]
This looks great; reviewing notebooks is a pain, though.

A few questions:
1) Are these notebooks supposed to follow DM style guide/flake8 formatting?
2) For the final 2x2 plots, it's also possible to get per-tract property maps (not consolidated).  I don't know if this would make the tutorial more complicated or less complicated.  But you can get the file with a dataset type without the consolidated, and a data id that includes tract, skymap, and band.
3) Also for those, I guess skyproj didn't work for the sub-plots?  If not, could you file an issue on skyproj?

**Comment by kadrlica** [comment]
Thanks Eli.

1. They should follow our CET flake8 style. I'll flake8 it again... (or maybe I didn't before).
2. That is interesting. I'll take a look. Personally, I think the notebook works well as is.
3. I doubt that Melissa tried skyproj, and I don't think it is really necessary here. My guess is that she tried something like:

```
# Set the figure's projection to be the WCS of the calexp
plt.subplot(projection=WCS(calexp.getWcs().getFitsMetadata()))
```

**Comment by erykoff** [comment]
Looks good!  Formatting of the code looks correct now (thanks `flake8`!).  I definitely don't think that (2) is necessary, but wanted to point it out.  And for (3) I was just curious if there was a problem with skyproj, I haven't actually tried this, but I will on my own time.

**Review by erykoff — APPROVED** [review]
Looks good to me!

**Review by MelissaGraham — APPROVED** [review]
Wonderful. I also updated the README.md to add this new NB.

**Pull request merged**
